#!/bin/sh
#
# @name Tiltquad
#
# @class Copter
# @type Quadrotor with 2-DOF Tilt
#
# @output Motor1 motor 1 (Front-Left)
# @output Motor2 motor 2 (Rear-Left)
# @output Motor3 motor 3 (Front-Right)
# @output Motor4 motor 4 (Rear-Right)
# @output Servo1 M1 Roll Tilt Servo
# @output Servo2 M1 Pitch Tilt Servo
# @output Servo3 M2 Roll Tilt Servo
# @output Servo4 M2 Pitch Tilt Servo
# @output Servo5 M3 Roll Tilt Servo
# @output Servo6 M3 Pitch Tilt Servo
# @output Servo7 M4 Roll Tilt Servo
# @output Servo8 M4 Pitch Tilt Servo
#
# @board bitcraze_crazyflie exclude
# @board px4_fmu-v2 exclude
#

. ${R}etc/init.d/rc.mc_defaults

# MAV_TYPE: QUADROTOR
param set-default MAV_TYPE 2
# 自定义Tiltquad
param set-default CA_AIRFRAME 16

param set-default CA_TILTQUAD_MAX_TILT 90

# Rotors
param set-default CA_ROTOR_COUNT 4

# Motor 1 (Front-Left)
param set-default CA_ROTOR0_PX 0.127
param set-default CA_ROTOR0_PY 0.127
param set-default CA_ROTOR0_TR 1
param set-default CA_ROTOR0_TP 1
# Rotor2
param set-default CA_ROTOR1_PX -0.127
param set-default CA_ROTOR1_PY -0.127
param set-default CA_ROTOR1_TR 2
param set-default CA_ROTOR1_TP 2
# Rotor3
param set-default CA_ROTOR2_PX 0.127
param set-default CA_ROTOR2_PY -0.127
param set-default CA_ROTOR2_TR 3
param set-default CA_ROTOR2_TP 3
# Rotor4
param set-default CA_ROTOR3_PX -0.127
param set-default CA_ROTOR3_PY 0.127
param set-default CA_ROTOR3_TR 4
param set-default CA_ROTOR3_TP 4

# Servos
param set-default CA_SV_TL_COUNT 8
# Servo0
param set-default CA_SV_TL0_CT 4    # Roll
param set-default CA_SV_TL0_AX 1
param set-default CA_SV_TL0_MAXA 90
param set-default CA_SV_TL0_MINA -90
param set-default CA_SV_TL0_MAXA 90
param set-default CA_SV_TL0_TD 0

# M1 Pitch Servo (PWM 6)
param set-default CA_SV_TL1_CT 2
param set-default CA_SV_TL1_AX 0
param set-default CA_SV_TL1_MINA -90
param set-default CA_SV_TL1_MAXA 90
param set-default CA_SV_TL1_TD 0

# ---- Motor 2 Tilt Servos ----
# M2 Roll Servo (PWM 7)
param set-default CA_SV_TL2_CT 4
param set-default CA_SV_TL2_AX 1
param set-default CA_SV_TL2_MINA -90
param set-default CA_SV_TL2_MAXA 90
param set-default CA_SV_TL2_TD 0

# M2 Pitch Servo (PWM 8)
param set-default CA_SV_TL3_CT 2
param set-default CA_SV_TL3_AX 0
param set-default CA_SV_TL3_MINA -90
param set-default CA_SV_TL3_MAXA 90
param set-default CA_SV_TL3_TD 0

# ---- Motor 3 Tilt Servos ----
# M3 Roll Servo (PWM 9)
param set-default CA_SV_TL4_CT 4
param set-default CA_SV_TL4_AX 1
param set-default CA_SV_TL4_MINA -90
param set-default CA_SV_TL4_MAXA 90
param set-default CA_SV_TL4_TD 0

# M3 Pitch Servo (PWM 10)
param set-default CA_SV_TL5_CT 2
param set-default CA_SV_TL5_AX 0
param set-default CA_SV_TL5_MINA -90
param set-default CA_SV_TL5_MAXA 90
param set-default CA_SV_TL5_TD 0

# ---- Motor 4 Tilt Servos ----
# M4 Roll Servo (PWM 11)
param set-default CA_SV_TL6_CT 4
param set-default CA_SV_TL6_AX 1
param set-default CA_SV_TL6_MINA -90
param set-default CA_SV_TL6_MAXA 90
param set-default CA_SV_TL6_TD 0

# M4 Pitch Servo (PWM 12)
param set-default CA_SV_TL7_CT 2
param set-default CA_SV_TL7_AX 0
param set-default CA_SV_TL7_MINA -90
param set-default CA_SV_TL7_MAXA 90
param set-default CA_SV_TL7_TD 0

# ==================== Tiltquad Specific Parameters ====================
# Flight Mode: 0 = MODE1 (±90° free tilt), 1 = MODE2 (±5° tilt lock)
param set-default CA_TILTQUAD_MODE 0

# Maximum tilt angle for MODE2 (degrees)
param set-default CA_TILT_MAX_ANG 5

# RC Channel for mode switching (0 = disabled, 1-8 = RC channels)
param set-default CA_TILT_RC_CHN 0
