#!/bin/sh
#
# @name Tiltquad
#
# @class Copter
# @type Quadrotor with 2-DOF Tilt
#
# @output Motor1 motor 1 (Front-Right)
# @output Motor2 motor 2 (Rear-Left)
# @output Motor3 motor 3 (Front-Left)
# @output Motor4 motor 4 (Rear-Right)
# @output Servo1 M1 Roll Tilt Servo (TL0)
# @output Servo2 M1 Pitch Tilt Servo (TL1)
# @output Servo3 M2 Roll Tilt Servo (TL2)
# @output Servo4 M2 Pitch Tilt Servo (TL3)
# @output Servo5 M3 Roll Tilt Servo (TL4)
# @output Servo6 M3 Pitch Tilt Servo (TL5)
# @output Servo7 M4 Roll Tilt Servo (TL6)
# @output Servo8 M4 Pitch Tilt Servo (TL7)
#
# @board bitcraze_crazyflie exclude
# @board px4_fmu-v2 exclude
#

. ${R}etc/init.d/rc.mc_defaults

# MAV_TYPE: QUADROTOR
param set-default MAV_TYPE 2
# 自定义Tiltquad
param set-default CA_AIRFRAME 16

# Rotors
# Motor order: M1 Front-Right, M2 Rear-Left, M3 Front-Left, M4 Rear-Right
# Servo order: TL0/TL1, TL2/TL3, TL4/TL5, TL6/TL7 = roll/pitch pairs for M1..M4
param set-default CA_ROTOR_COUNT 4

# Motor 1 (Front-Right)
param set-default CA_ROTOR0_PX 0.127
param set-default CA_ROTOR0_PY 0.127
param set-default CA_ROTOR0_TR 1
param set-default CA_ROTOR0_TP 1
# Rotor2
param set-default CA_ROTOR1_PX -0.127
param set-default CA_ROTOR1_PY -0.127
param set-default CA_ROTOR1_TR 2
param set-default CA_ROTOR1_TP 2
# Rotor3
param set-default CA_ROTOR2_PX 0.127
param set-default CA_ROTOR2_PY -0.127
param set-default CA_ROTOR2_TR 3
param set-default CA_ROTOR2_TP 3
# Rotor4
param set-default CA_ROTOR3_PX -0.127
param set-default CA_ROTOR3_PY 0.127
param set-default CA_ROTOR3_TR 4
param set-default CA_ROTOR3_TP 4

# Servos
# Tilt servo layout: [TL0 roll, TL1 pitch, TL2 roll, TL3 pitch, TL4 roll, TL5 pitch, TL6 roll, TL7 pitch]
param set-default CA_SV_TL_COUNT 8
# TL0: M1 Roll Servo
param set-default CA_SV_TL0_CT 4    # Roll
param set-default CA_SV_TL0_AX 1
param set-default CA_SV_TL0_MINA -12
param set-default CA_SV_TL0_MAXA 12
# Roll-like 正倾转指向机体右侧（+Y）
param set-default CA_SV_TL0_TD 90
param set-default CA_SV0_SLEW 1.5

# M1 Pitch Servo (PWM 6)
param set-default CA_SV_TL1_CT 2
param set-default CA_SV_TL1_AX 0
param set-default CA_SV_TL1_MINA -12
param set-default CA_SV_TL1_MAXA 12
# Pitch-like 正倾转指向机体前方（+X）
param set-default CA_SV_TL1_TD 0
param set-default CA_SV1_SLEW 1.5

# ---- Motor 2 Tilt Servos ----
# M2 Roll Servo (PWM 7)
param set-default CA_SV_TL2_CT 4
param set-default CA_SV_TL2_AX 1
param set-default CA_SV_TL2_MINA -12
param set-default CA_SV_TL2_MAXA 12
param set-default CA_SV_TL2_TD 90
param set-default CA_SV2_SLEW 1.5

# M2 Pitch Servo (PWM 8)
param set-default CA_SV_TL3_CT 2
param set-default CA_SV_TL3_AX 0
param set-default CA_SV_TL3_MINA -12
param set-default CA_SV_TL3_MAXA 12
param set-default CA_SV_TL3_TD 0
param set-default CA_SV3_SLEW 1.5

# ---- Motor 3 Tilt Servos ----
# M3 Roll Servo (PWM 9)
param set-default CA_SV_TL4_CT 4
param set-default CA_SV_TL4_AX 1
param set-default CA_SV_TL4_MINA -12
param set-default CA_SV_TL4_MAXA 12
param set-default CA_SV_TL4_TD 90
param set-default CA_SV4_SLEW 1.5

# M3 Pitch Servo (PWM 10)
param set-default CA_SV_TL5_CT 2
param set-default CA_SV_TL5_AX 0
param set-default CA_SV_TL5_MINA -12
param set-default CA_SV_TL5_MAXA 12
param set-default CA_SV_TL5_TD 0
param set-default CA_SV5_SLEW 1.5

# ---- Motor 4 Tilt Servos ----
# M4 Roll Servo (PWM 11)
param set-default CA_SV_TL6_CT 4
param set-default CA_SV_TL6_AX 1
param set-default CA_SV_TL6_MINA -12
param set-default CA_SV_TL6_MAXA 12
param set-default CA_SV_TL6_TD 90
param set-default CA_SV6_SLEW 1.5

# M4 Pitch Servo (PWM 12)
param set-default CA_SV_TL7_CT 2
param set-default CA_SV_TL7_AX 0
param set-default CA_SV_TL7_MINA -12
param set-default CA_SV_TL7_MAXA 12
param set-default CA_SV_TL7_TD 0
param set-default CA_SV7_SLEW 1.5
